Feng_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^about$', views.about, name='about'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# from markdownx.models import MarkdownxField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# class Tag(models.Model):
#     name = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name

class Post(models.Model):
    """
    title：题目；
    body：文章内容；
    created_time：创建时间；
    modified_time：最后一次修改时间；
    author：作者；
    category：博文分类；
    tags：标签；
    views：阅读量；
    """
    title = models.CharField(max_length=70)
    body = models.TextField()
    # body = MarkdownxField()

    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    category = models.ForeignKey(Category)
    # tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)

    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        '''
        增加阅读量
        '''
        self.views += 1
        self.save(update_fields=['views'])

class AboutMe(models.Model):
    title = models.CharField(max_length=70)
    # body = MarkdownxField()
    body = models.TextField()
    subheading = models.CharField(max_length=70, blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, AboutMe, Category
import markdown
# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })

def category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=category).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.body = markdown.markdown(post.body, extensions = [
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    post.increase_views() # 阅读量 + 1

    return render(request, 'blog/detail.html', context={'post': post})

def about(request):
    aboutme = get_object_or_404(AboutMe)
    aboutme.body = markdown.markdown(aboutme.body, extensions = [
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    return render(request, 'blog/about.html', context={'about': aboutme})

templates/base.html
{% load staticfiles %}

<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-site-verification" content="wGSnp3FNccPZtlpoDCkd8Qm6WYxIEBaG9l5axgVK6Y4" />
    {% block title %}
    {% endblock title %}
    <!--Icon image-->
    <link rel="icon shortcut" href="{% static 'blog/image/milk.png' %}" />



    <!-- Bootstrap core CSS -->
    <!--<link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!--<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/zgithub.css' %}">


  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <!--<a class="navbar-brand" href="{% url 'blog:index' %}">Vent</a>-->
        <h5 class="navbar-brand">Vent</h5>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">About Me</a>
            </li>
            <!--<li class="nav-item">-->
              <!--<a class="nav-link" href="http://127.0.0.1:8000/admin/">Login</a>-->
            <!--</li>-->
            <!--<li class="nav-item">-->
              <!--<a class="nav-link" href="contact.html">Contact</a>-->
            <!--</li>-->
          </ul>
        </div>
      </div>
    </nav>

    <main>
    	{% block main %}
    	{% endblock main %}
    </main>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/pourquoizzz">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/profile.php?id=100009478115707">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/xfffrank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy;<a href="http://www.miitbeian.gov.cn/">粤ICP备17129326号</a></p>

          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <!--<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>-->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Custom scripts for this template -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

  </body>

</html>

templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>{{ about.title }}</title>
{% endblock title %}

{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('http://oyzb8rudl.bkt.clouddn.com/le_vent.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>{{ about.title }}</h1>
                    <span class="subheading">{{ about.subheading }}</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{ about.body | safe }}
            <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates-->
                <!--odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus-->
                <!--consectetur?</p>-->
            <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque-->
                <!--architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in-->
                <!--officia voluptas voluptatibus, minus!</p>-->
            <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente-->
                <!--qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti-->
                <!--enim modi! Et.</p>-->
        </div>
    </div>
</div>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
<title>{{ post.title }}</title>
{% endblock title %}

{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('http://oyzb8rudl.bkt.clouddn.com/le_vent.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{ post.title }}</h1>
                    <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
                    <span class="meta">
                        <time datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                        Category: <a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a>
                        Read: {{ post.views }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {{ post.body | safe }}
            </div>
        </div>
    </div>
</article>

{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}{% load staticfiles %}{% block title %}<title>Le vent se lève</title>{% endblock title %}{% block main %}<!-- Page Header --><header class="masthead" style="background-image: url('http://oyzb8rudl.bkt.clouddn.com/le_vent.jpg')">    <div class="overlay"></div>    <div class="container">        <div class="row">            <div class="col-lg-8 col-md-10 mx-auto">                <div class="site-heading">                    <h1>Le vent se lève</h1>                    <span class="subheading">il faut tenter de vivre</span>                </div>            </div>        </div>    </div></header><!-- Main Content --><div class="container">    <div class="row">        <div class="col-lg-8 col-md-10 mx-auto">            {% for post in post_list %}            <div class="post-preview">                <a href="{{ post.get_absolute_url }}">                    <h2 class="post-title">                        {{ post.title }}                    </h2>                </a>                <p class="post-meta">                    <time datetime="{{ post.created_time }}">{{ post.created_time }}</time>                        Category: <a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a>                        Read: {{ post.views }}                </p>            </div>            <hr>            {% empty %}            <div class="post-preview">暂时没有发布文章</div>            {% endfor %}        </div>    </div></div>{% endblock main %}